name: Membership

on:
  push:
    branches:
      - features/membership

env:
  REGISTRY: "registry.digitalocean.com/private-registry"
  IMAGE_NAME: "member"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create Docker config file
        run: echo "${{ secrets.DOCKER_CONFIG_JSON }}" > $HOME/.docker/config.json
        
      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.66.0/doctl-1.66.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin


      - name: Log in to DigitalOcean Container Registry
        run: doctl auth init -t ${{ secrets.REGISTRY_TOKEN }}

        
      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
        
      - name: Tag & Push image to DigitalOcean Container Registry
        run: |
          doctl registry login
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}




  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker pull $REGISTRY/$IMAGE_NAME:${{ github.sha }}
            docker run -d --name member -p 8000:8000 $REGISTRY/$IMAGE_NAME:${{ github.sha }}
